-- RandomDayGuard/config.lua
-- Saved-folder, log-driven server watchdog configuration.
-- Admin.ini receives clean BannedPlayer=<ID> lines only. Reasons are written to runtime evidence files.

return {
    enabled = true,
    version = "v0.4.11-alpha",
    server_label = "RandomDayGuard Server",

    whitelist = {
        -- Add trusted server-owner or administrator account IDs here.
        -- Example format: ["00000000000000000"] = true,
    },

    saved = {
        root_candidates = {
            "../../../../../Saved",
            "../../../../../../Saved",
            "../../../../../../AbioticFactor/Saved",
            "Saved",
            "./Saved",
            "../Saved",
            "../../Saved",
            "AbioticFactor/Saved",
            "./AbioticFactor/Saved",
            "/AMP/abiotic-factor/2857200/AbioticFactor/Saved",
            "Z:/AMP/abiotic-factor/2857200/AbioticFactor/Saved",
        },
        direct_known_files = {
            "Logs/AbioticFactor.log",
            "Logs/AbioticFactor-backup.log",
            "Logs/AbioticFactor.log.1",
            "SaveGames/Server/Admin.ini",
            "SaveGames/Server/SandboxSettings.ini",
            "Config/WindowsServer/SandboxSettings.ini",
            ".autoExclude",
        },
        scan_logs = true,
        scan_world_saves = true,
        scan_player_data = true,
        scan_backups = true,
        trust_filenames = false,
        prefer_internal_content_identity = true,
        allow_full_find_discovery = false,
    },

    log_tail = {
        enabled = true,
        start_at_end_on_first_run = true,
        tail_backup_logs = false,
        register_backup_logs = true,
        backfill_backup_logs_on_start = false,
        backfill_active_log_on_boot = false,
        offset_file = "runtime/log_offsets.tsv",
        max_lines_per_poll = 500,
        max_bytes_per_poll = 262144,
    },

    runtime = {
        poll_interval_ms = 1000,
        heartbeat_interval_seconds = 10,
        max_poll_runtime_ms = 250,
        max_lines_per_poll = 500,
        max_bytes_per_poll = 262144,
        max_events_per_poll = 200,
        full_scan_interval_seconds = 300,
        object_registry_interval_seconds = 300,
        report_refresh_interval_seconds = 30,
        cleanup_interval_seconds = 600,
        weekly_summary_check_interval_seconds = 3600,
    },

    logging = {
        low_importance_mode = "aggregate",
        low_importance_sample_interval_seconds = 60,
        max_low_importance_actor_events_per_session = 200,
        max_actor_touch_events_per_poll = 100,
        max_actor_touch_events_per_session = 1000,
        write_low_importance_raw_events = false,
        escalate_low_to_medium_when_correlated = true,
    },

    retention = {
        detailed_retention_days = 7,
        daily_summary_retention_days = 90,
        weekly_summary_retention_weeks = 12,
        rotate_jsonl_when_bytes_exceed = 5242880,
        max_raw_events_lines = 20000,
        max_low_importance_events_per_day = 5000,
        max_actor_touch_rollups_per_day = 10000,
        max_recent_event_keys = 5000,
        max_warning_reports = 30,
        max_raid_cases = 200,
        compact_json_outputs = true,
        archive_rotated_runtime_logs = false,
        routine_log_days = 7,
        warning_report_days = 7,
        keep_enforced_forever = true,
        keep_evidence_forever = true,
        keep_banned_raid_cases_forever = true,
        create_warning_file_only_when_player_joins = true,
        create_empty_warning_files = false,
        carry_open_cases_forward = true,
    },

    scanning = {
        full_scan_on_start = true,
        reuse_completed_baseline = true,
        resume_incomplete_scan = true,
        incremental_refresh_after_baseline = true,
        force_full_scan = false,
        partial_output_interval_seconds = 30,
        checkpoint_interval_seconds = 15,
        checkpoint_interval_files = 25,
        baseline_manifest_enabled = true,
        per_file_entry_cache_enabled = true,
        changed_file_detection = true,
        full_scan_max_age_hours = 168,
        aggressive_first_baseline = true,
        targeted_token_extraction = true,
        fallback_broad_token_scan = false,
        deep_backup_scan_enabled = false,
        incremental_scan_enabled = true,
        allow_full_find_discovery = true,
        allow_full_find_discovery_only_in_scan_job = true,
        recursive_discovery_enabled = true,
        recursive_discovery_mode = "manifest",
        discovery_files_per_tick = 200,
        discovery_max_runtime_ms = 100,
        startup_scan_files_per_tick = 25,
        startup_scan_max_bytes_per_tick = 4194304,
        startup_scan_max_runtime_ms = 100,
        write_scan_progress = true,
        full_scan_when_no_players_online = true,
        scan_on_log_failure_event = true,
        scan_on_warning_burst = true,
        scan_on_join_wave = true,
        heavy_scan_min_interval_seconds = 300,
        max_file_bytes = 1048576,
        rescan_only_changed_files = true,
        direct_file_fallback = true,
    },

    admin_ini = {
        enabled = true,
        backup_before_write = true,
        prevent_duplicates = true,
        preserve_external_changes = true,
        write_comments = false,
        atomic_write = true,
        relative_path = "SaveGames/Server/Admin.ini",
    },

    object_registry = {
        enabled = true,
        auto_register_new_classes = true,
        first_run_new_classes_are_baseline = true,
        new_class_enforcement = "log_only",
        scan_patterns = {
            "Deployed_", "Container_", "Item_", "ResourceNode_", "NPCSpawn_",
            "PowerSocket", "PlugStrip", "Plugboard", "Battery", "Teleporter",
            "Portal", "Bridge", "Barricade", "Furniture", "Food", "Weapon",
            "Tool", "Armor", "Trinket", "PetBed", "PestWheel", "LootSpillBag",
            "/Game/Maps/", "/Game/", "/Script/", "PersistentLevel", "_C"
        },
    },

    class_categories = {
        deployed = { patterns = {"Deployed_"} },
        containers = { patterns = {"Container_", "LootSpillBag"} },
        items = { patterns = {"Item_"} },
        power_context = { patterns = {"PowerSocket", "PlugStrip", "Plugboard", "Battery", "LaserPowerConverter", "LaserEmitter", "CableReroute"} },
        transport = { patterns = {"Teleporter", "Portal"} },
        beds_spawn = { patterns = {"Bed", "Cot", "PetBed"} },
        bridge_support = { patterns = {"Bridge", "Barricade", "Support", "Wall"} },
        npc_resource = { patterns = {"NPCSpawn_", "ResourceNode_"} },
        map_asset_path = { patterns = {"/Game/Maps/", "PersistentLevel"} },
    },

    high_risk_classes = {
        enabled = true,
        seed_classes = {
            "Deployed_PestWheel", "Deployed_PetBed", "Deployed_TeleporterPad",
            "Deployed_CableReroute", "Deployed_PlugStrip", "Deployed_LaserPowerConverter",
            "Deployed_LaserEmitter", "Deployed_Battery", "Container_LootSpillBag",
            "Deployed_Furniture_RES_Bed", "PetBed", "Cot", "Bridge", "Barricade", "Container"
        },
    },

    accumulation = {
        enabled = true,
        count_alone_never_bans = true,
        compare_start_to_latest = true,
        compare_previous_baseline = true,
        compare_backup_if_available = true,
        watched_delta_classes = {
            "Deployed_PestWheel", "Deployed_PetBed", "Container_LootSpillBag",
            "Deployed_TeleporterPad", "Deployed_CableReroute", "Bridge", "Container"
        },
        review_delta_total = 10,
        critical_delta_total = 25,
        critical_single_class_delta = {
            Deployed_PestWheel = 1,
            Deployed_TeleporterPad = 1,
            Container_LootSpillBag = 5,
            Deployed_CableReroute = 20,
            Deployed_PetBed = 10,
        },
        require_target_context_for_enforcement = true,
        require_account_correlation_for_enforcement = true,
    },

    target_context = {
        enabled = true,
        detect_far_from_power_context = true,
        detect_mostly_player_deployed = true,
        detect_extreme_relative_coordinates = true,
        detect_isolated_cluster = true,
        no_power_context_is_evidence_only = true,
        filename_identity_is_weak = true,
    },

    warning_bursts = {
        enabled = true,
        deployable_save_warning = { enabled = true, review_count = 5, critical_count = 20, window_minutes = 10, correlate_to_active_players = true },
        actor_channel_failure = { enabled = true, review_count = 20, critical_count = 100, window_minutes = 10, correlate_to_active_players = true },
        update_actor_to_worldsave = { enabled = true, review_count = 500, critical_count = 2000, window_minutes = 10, correlate_to_active_players = true, enforcement_by_itself = false },
    },

    crash_correlation = {
        enabled = true,
        single_crash_never_bans = true,
        active_before_failure_minutes = 5,
        repeated_failure_review_count = 2,
        repeated_failure_ban_count = 3,
        require_same_account = true,
        require_non_whitelist = true,
        rolling_history_days = 7,
    },

    join_leave = {
        enabled = true,
        churn_alone_never_bans = true,
        rolling_history_days = 7,
        join_wave_window_minutes = 10,
        join_wave_min_accounts = 3,
    },

    server_lifecycle = {
        startup_grace_seconds = 180,
        shutdown_grace_seconds = 120,
        post_crash_reconnect_grace_seconds = 300,
        normal_restart_suppression_seconds = 300,
        lifecycle_events_are_context_only = true,
        close_sessions_on_crash = true,
        close_sessions_on_graceful_shutdown = true,
        dedupe_rotated_backup_logs = true,
    },

    raid_detection = {
        enabled = true,
        rolling_history_days = 7,
        create_case_min_accounts = 2,
        critical_case_min_accounts = 3,
        link_by_same_warning_burst = true,
        link_by_same_failure_window = true,
        link_by_rejoin_after_failure = true,
        ban_all_accounts_in_case = false,
        require_account_specific_evidence = true,
        central_account_auto_ban_score = 140,
        central_account_review_score = 80,
    },

    warning_report = {
        enabled = true,
        rotation_days = 7,
        create_file_only_when_player_joins = true,
        create_empty_warning_files = false,
        group_by_player = true,
        group_by_session = true,
        include_server_context = true,
        include_other_active_players = true,
        include_detector_explanations = true,
        include_threshold_status = true,
        include_ban_decision = true,
        max_log_snippets_per_session = 30,
        max_warning_lines_per_player = 200,
        archive_old_reports = true,
    },

    world_state = {
        enabled = true,
        write_boot_state = true,
        write_current_state = true,
        write_session_join_state = true,
        write_session_latest_state = true,
        write_session_leave_state = true,
        write_session_diff = true,
        update_session_latest_on_warning_burst = true,
        update_session_latest_on_failure = true,
        update_session_latest_on_join_wave = true,
    },

    ping = {
        enabled = false,
        mode = "log",
        sample_interval_seconds = 10,
        average_ping_warn_ms = 250,
        average_ping_critical_ms = 400,
        ban_on_ping_alone = false,
    },

    enforcement = {
        enabled = true,
        auto_ban = false,
        review_only_mode = true,
        write_admin_ini = false,
        request_restart_after_ban = false,
        require_playerdata_verified = false,
        require_clean_ban_id = true,
        preserve_moderators = true,
        preserve_existing_bans = true,
        ban_on_threshold = true,
        trusted_ids = {},
        auto_ban_score = 140,
        review_score = 80,
        ban_from_lag_alone = false,
        ban_from_ping_alone = false,
        ban_from_object_count_alone = false,
        ban_from_single_crash = false,
        ban_from_single_warning_burst = false,
        ban_from_unknown_id = false,
        require_account_specific_evidence = true,
        thresholds = {
            repeated_warning_burst_correlation = 3,
            repeated_failure_correlation = 3,
            only_nonwhitelist_active_during_critical_change = 2,
            raid_case_central_account_score = 140,
            active_during_target_accumulation = 2,
        },
    },

    amp = {
        enabled = true,
        request_restart_after_ban = true,
        restart_marker_file = "runtime/request_restart.flag",
        restart_reason_file = "runtime/restart_reason.json",
        restart_min_interval_minutes = 15,
        max_restarts_per_hour = 2,
    },
}
